### ISSUE TITLE
[Question]: Accessibility with Screen Readers? 

### ISSUE THREAD

**Issue by Zireael07** [MarketingPipeline/Termino.js#1]
Does this work with screen readers? Asking because I want to use it for a MUD, and I know it's a genre with many sight impaired players...

**Comment by MarketingPip** [comment]
That I'm not sure of. If you use proper HTML with accessibility usage. I would ASSUME it will work. 


Tho - a report of this would be appreciated, if not working.👌

**Comment by MarketingPip** [comment]
As for now I am going to be closing this issue / question @Zireael07 - feel free to re-open it as a new issue under a bug report if not working correctly. :+1:

**Comment by MarketingPip** [comment]
@Zireael07 - are you still making a MUD based game? If so can I add you to a private repo to discuss something that might be of interest to you for contributing to etc?

**Comment by Zireael07** [comment]
Go ahead - my work on that MUD is veeery slow but I'm still interested in various tech
